### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by zhaozhengChen** [ElementAI/embedding-propagation#11]
Hi authors,
Are there pre-trained models I can use? I found it take a long time to pre-train.
Thank you!

**Comment by prlz77** [comment]
Hi! Here you have! https://drive.google.com/drive/folders/1M1ALzZax4FTv1tjWMAYPhYXTJoH_iriZ?usp=sharing

Sorry for the delay, I had to look for them.

**Comment by zhaozhengChen** [comment]
Thanks! 
Could you please also release the fine-tuned models?

**Comment by prlz77** [comment]
Here they are https://drive.google.com/drive/folders/1RJptAcZsBixkdJmhKpDoYhPKxlApTcQW?usp=sharing

**Comment by zhaozhengChen** [comment]
Thanks!
