### ISSUE TITLE
Some codes in 'global_consistency' seems wrong

### ISSUE THREAD

**Issue by LinglanZhao** [ElementAI/embedding-propagation#13]
Hi! Thanks for your transparent work！
I find some codes in https://github.com/ElementAI/embedding-propagation/blob/master/embedding_propagation/embedding_propagation.py#L96 seems wrong because the size of tensor mismatchs at non-singleton dimension.  This implementation is also contrary to that in https://github.com/ElementAI/embedding-propagation/blob/e7bfc719ac39af027456d0404bffccb52db681dc/src/models/base_ssl/distances.py#L587. @prlz77 @IssamLaradji

**Comment by LinglanZhao** [comment]
Maybe https://github.com/ElementAI/embedding-propagation/blob/master/embedding_propagation/embedding_propagation.py#L85 `weights: Tensor of shape (batch, n, n)` should be `weights: Tensor of shape (n, n)`?

**Comment by prlz77** [comment]
Your are right, the documentation is wrong. It receives a tensor of size (n,n). I have accordingly fixed it. Thanks for pointing it out!
