### ISSUE TITLE
Issues with the data

### ISSUE THREAD

**Issue by cadurosar** [ElementAI/embedding-propagation#2]
Hi,

thanks for the code for reproducing your experiments. I've tried to run it, but I had a problem with the data. When I download the data from the gdrive links I get files that are called dataset-train.pkl, dataset-val.pkl... but when I try to run the code I get this error message:
"FileNotFoundError: [Errno 2] No such file or directory: './data/mini-imagenet/mini-imagenet-train.npz'"
Which calls for a .npz file and not .pkl. Could you help me find what I'm doing wrong?

Thanks

Carlos

**Comment by prlz77** [comment]
Hi @cadurosar,

Thanks for pointing this out. We used the same pre-processing as [TADAM](https://github.com/ElementAI/TADAM/blob/master/datasets/create_dataset_miniImagenet.py) applied on the [raw data](https://drive.google.com/open?id=16V_ZlkW4SsnNDtnGmaBRq2OoPmUOc5mY) .

For the moment you can just do that. We will adapt it to a more available format as soon as possible.

**Comment by bkj** [comment]
I don't think the TADAM preprocessing works on the link you sent -- the contents of that file are
```
mini-imagenet-cache-train.pkl
mini-imagenet-cache-val.pkl
mini-imagenet-cache-test.pkl
```
but TADAM is looking for an `images.zip` file.  Thoughts?

**Comment by prlz77** [comment]
Hi, I have checked again and you are right, it directly needs the ILSVRC2012 downloaded images, and the CSV files in TADAM.

**Comment by prlz77** [comment]
[Update] The TADAM mini-imagenet creator is a python port of the original one from Ravi & Larochelle https://github.com/twitter/meta-learning-lstm/blob/master/dataset/miniImagenet.lua

I think they just select the raw images from the information in the CSVs and create a zip from there. Then, they apply the data processing to the zip. You can just skip the zip part and read them from disk though.

Anyway, the procedure is suboptimal given that there already exist pickled versions of the dataset, so I'll try to provide a dataloader in the future.

**Comment by cadurosar** [comment]
Would you be able to point me to the pickle version of the dataset?

**Comment by prlz77** [comment]
I meant the ones found here https://github.com/renmengye/few-shot-ssl-public or here https://drive.google.com/drive/folders/137M9jEv8nw0agovbUiEN_fPl_waJ2jIj

In the last link you can also download the jpgs but I think they are already processed so you can just convert them to npz in the same format required by our dataloader https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html

**Comment by cadurosar** [comment]
Ah okay thank you for the clarification. I will do as you suggest.

**Comment by prlz77** [comment]
Hey @cadurosar @bkj , I have added `class EpisodicMiniImagenetPkl(EpisodicDataset):` to the code :)

You can use it by setting the dataset name to `"episodic_miniimagenet_pkl"` in `exp_configs`.

I cannot guarantee reproducibility with this one though, but you should get roughly the same results.
