### ISSUE TITLE
problem about multi gpu 

### ISSUE THREAD

**Issue by invokerpicker** [ElementAI/embedding-propagation#23]
Hi, thank you for your release!
The adjacency matrix computing needs all embeddings together. However the code is using dataparallel on multi gpus. In this situation, the adjacency matix computing can only uses part of the embeddings in a single gpu. Using single gpu and multi gpus has different results.  I'm wondering the solution for such a problem.

**Comment by prlz77** [comment]
Hi @invokerpicker, thanks for the interest in our work! We perform embedding propagation **after** extracting embeddings with DataParallel such that all of them are together in the same GPU.

1. Extract embeddings: https://github.com/ElementAI/embedding-propagation/blob/master/src/models/finetuning.py#L140
2. Embedding prop: https://github.com/ElementAI/embedding-propagation/blob/master/src/models/finetuning.py#L145

I hope this solves your question.

**Comment by invokerpicker** [comment]
> 

Thanks!
