### ISSUE TITLE
Effect of Batch Size

### ISSUE THREAD

**Issue by Dhul-Husni** [ElementAI/embedding-propagation#25]
Hi, awesome project. 

For embedding propagation what is your intuition on how the batch size affects the intra-cluster homogeneity and inter-cluster separation? This is not with regards to training but with regards to EP being a function applied to the results of a feature extractor. I can imagine smaller batch sizes lead to more local homogeneity and larger batch sizes consider global homogeneity, is my intuition correct? Is there a systematic way to find a good batch size?

**Comment by prlz77** [comment]
Hi thanks!

We applied embedding propagation to each episode independently without considering batches, thus the batch size has no influence on the results of EP. However, the shot number does have an effect! This is not studied in depth in our paper. And we found the best alpha by cross-validation.

Hope this clarifies your question,

Pau

**Comment by Dhul-Husni** [comment]
Thanks Pau, this does.
