### ISSUE TITLE
Issues about ssl

### ISSUE THREAD

**Issue by SisinHuang** [ElementAI/embedding-propagation#3]
Hi,

Thanks for sharing your code, it's an excellent learning material. 
I have problems in running ssl experiment. In the 'ssl_exps.py', it seems that ssl needs some specific 'exp_dict.json'. How can I get these files?

Thanks

Sisin

**Comment by cvprkang** [comment]
+1

**Comment by prlz77** [comment]
Hi @SisinHuang @cvprkang, we have updated the code with the SSL experiments, and the README with instructions to run it. We haven't finished updating the code but I think it should already work. Please, let us know if there were any problems.

**Comment by SisinHuang** [comment]
Get it!
Sorry for my slow reply.
