### ISSUE TITLE
Pretraining

### ISSUE THREAD

**Issue by cvprkang** [ElementAI/embedding-propagation#6]
In the pre-training process, is it possible to directly consider the three data sets to pre-train together? Shouldn't it be a training set of data that is pre-trained and then fine-tuned for testing on that data set?

**Comment by prlz77** [comment]
Hi @cvprkang, if you want to train on multiple datasets I recommend you to take a look at the meta-dataset paper.

I am not sure I understand the second question, could you provide more details?
