### ISSUE TITLE
Can I run this code using all unlabeled images per novel class (e.g. 600 for miniImageNet)?

### ISSUE THREAD

**Issue by tankche1** [ElementAI/embedding-propagation#9]
Hi, I appreciate your work.
I wonder if I can run this code using all unlabeled images per novel class (e.g. 600 for miniImageNet).
If I can, what it the estimated performance from your view? Will there be a big improvement?

**Comment by prlz77** [comment]
Hi @tankche1! 

Yes, you can, but the matrix inverse will take some time. Maybe you could try to find an efficient approximation (see https://arxiv.org/pdf/1904.04717.pdf)
The performance will be better than with 100 samples (reported in the paper) but I doubt the performance increase will be higher than from 0 to 100. I remember that there were diminishing returns. 

If you try, I'd like to know the outcome!
